<a href="https://colab.research.google.com/github/ghanshyamverma4654/Mission-Data-Science/blob/master-branch/PANDAS_NOTES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PANDAS**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
labels = ["a","b","c","d","e"]
lst = [10,20,30,40,50]
arr = np.array([1,2,3,4,5])
d = {1:10,2:20,3:30,4:40,5:50}

In [ ]:
pd.Series(lst)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
pd.Series(lst,index=labels)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [ ]:
pd.Series(arr)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
pd.Series(d)

1    10
2    20
3    30
4    40
5    50
dtype: int64

**DATA FRAME**

In [ ]:
data = {
    "Name":["John","Ann","Parker","Linda"],
    "Age":[28,34,29,42],
    "City":["New York,","Paris","Berlin","London"],
    "Salary":[65000,70000,62000,85000]
}
data

{'Name': ['John', 'Ann', 'Parker', 'Linda'],
 'Age': [28, 34, 29, 42],
 'City': ['New York,', 'Paris', 'Berlin', 'London'],
 'Salary': [65000, 70000, 62000, 85000]}

In [ ]:
#Creating Data Frame

pd.DataFrame(data)

     Name  Age       City  Salary
0    John   28  New York,   65000
1     Ann   34      Paris   70000
2  Parker   29     Berlin   62000
3   Linda   42     London   85000

In [ ]:
pd.DataFrame(lst)

    0
0  10
1  20
2  30
3  40
4  50

In [ ]:
data_list = [
    ["John",28,"New York,","65000"],
    ["Ann",34,"Paris","70000"],
    ["Parker",29,"Berlin","62000"],
    ["Linda",42,"London","85000"]
]

In [ ]:
data_list

[['John', 28, 'New York,', '65000'],
 ['Ann', 34, 'Paris', '70000'],
 ['Parker', 29, 'Berlin', '62000'],
 ['Linda', 42, 'London', '85000']]

In [ ]:
pd.DataFrame(data_list) #No index

        0   1          2      3
0    John  28  New York,  65000
1     Ann  34      Paris  70000
2  Parker  29     Berlin  62000
3   Linda  42     London  85000

In [ ]:
#Creating labels for data_list
labels = ["Name","Age","City","Salary"]

In [ ]:
df = pd.DataFrame(data_list,columns = labels)

In [ ]:
df

     Name  Age       City Salary
0    John   28  New York,  65000
1     Ann   34      Paris  70000
2  Parker   29     Berlin  62000
3   Linda   42     London  85000

In [ ]:
#Selecting and Indexing Columns

df["Name"]

0      John
1       Ann
2    Parker
3     Linda
Name: Name, dtype: object

In [ ]:
df["Age"]

0    28
1    34
2    29
3    42
Name: Age, dtype: int64

In [ ]:
df[["Name","Age"]]

     Name  Age
0    John   28
1     Ann   34
2  Parker   29
3   Linda   42

In [ ]:
#Creating new column

df["Role"] = ["Doctor","Engineer","Accountant","Nurse"]
df

     Name  Age       City Salary        Role
0    John   28  New York,  65000      Doctor
1     Ann   34      Paris  70000    Engineer
2  Parker   29     Berlin  62000  Accountant
3   Linda   42     London  85000       Nurse

In [ ]:
df[["Name","Role"]]

     Name        Role
0    John      Doctor
1     Ann    Engineer
2  Parker  Accountant
3   Linda       Nurse

In [ ]:
#Removing a Column

df.drop("Role",axis=1) #It will not drop the column permanently

     Name  Age       City Salary
0    John   28  New York,  65000
1     Ann   34      Paris  70000
2  Parker   29     Berlin  62000
3   Linda   42     London  85000

In [ ]:
df

     Name  Age       City Salary        Role
0    John   28  New York,  65000      Doctor
1     Ann   34      Paris  70000    Engineer
2  Parker   29     Berlin  62000  Accountant
3   Linda   42     London  85000       Nurse

In [ ]:
df.drop("Role",axis = 1,inplace=True)#This will drop the column permanently

In [ ]:
df

     Name  Age       City Salary
0    John   28  New York,  65000
1     Ann   34      Paris  70000
2  Parker   29     Berlin  62000
3   Linda   42     London  85000

In [ ]:
#Dropping multiple columns

df.drop(["Salary","City"],axis=1,inplace=True)

In [ ]:
df

     Name  Age
0    John   28
1     Ann   34
2  Parker   29
3   Linda   42

In [ ]:
df.drop(0,axis=0,inplace=True) #Will drop the 0th row
df

     Name  Age
1     Ann   34
2  Parker   29
3   Linda   42

In [ ]:
df.drop(3,axis=0,inplace=True)#Dropping 3rd row
df

     Name  Age
1     Ann   34
2  Parker   29

In [ ]:
df

     Name  Age
1     Ann   34
2  Parker   29

In [ ]:
#Selecting Rows
df.loc[1]

Name    Ann
Age      34
Name: 1, dtype: object

In [ ]:
df.loc[[1,2]]

     Name  Age
1     Ann   34
2  Parker   29

In [ ]:
data = [
    ["Tony",27,"Below",80000],
    ["Marcus",36,"London",75000],
    ["Sarah",26,"New York",65000],
    ["William",30,"Berlin",83000],
    ["Ash",33,"Tokyo",89000]
]
labels = ["Name","Age","City","Salary"]
df1 = pd.DataFrame(data,columns=labels)
df1

      Name  Age      City  Salary
0     Tony   27     Below   80000
1   Marcus   36    London   75000
2    Sarah   26  New York   65000
3  William   30    Berlin   83000
4      Ash   33     Tokyo   89000

In [ ]:
#Selecting Specific Portion of the data frame
df1.loc[[2,3]][["Name","City","Salary"]]

      Name      City  Salary
2    Sarah  New York   65000
3  William    Berlin   83000

In [ ]:
#Conditional Selection

df1[df1["Salary"]>70000]

      Name  Age    City  Salary
0     Tony   27   Below   80000
1   Marcus   36  London   75000
3  William   30  Berlin   83000
4      Ash   33   Tokyo   89000

In [ ]:
df1[(df1["Age"] >= 30) & (df1["Salary"] > 80000)]

      Name  Age    City  Salary
3  William   30  Berlin   83000
4      Ash   33   Tokyo   89000

In [ ]:
df1

      Name  Age      City  Salary
0     Tony   27     Below   80000
1   Marcus   36    London   75000
2    Sarah   26  New York   65000
3  William   30    Berlin   83000
4      Ash   33     Tokyo   89000

**MISSING DATA**

In [ ]:
data = {
    "A":[1,2,np.nan,4,5],
    "B":[np.nan,2,3,4,5],
    "C":[1,2,3,np.nan,np.nan],
    "D":[1,2,np.nan,np.nan,5]
}

In [ ]:
df = pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  2.0
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

**SEARCHING NULL VALUES**

In [ ]:
df.isna()#row-wise

       A      B      C      D
0  False   True  False  False
1  False  False  False  False
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
df.isna().sum()#column-wise

A    1
B    1
C    2
D    2
dtype: int64

In [ ]:
df.isna().any() #column-wise

A    True
B    True
C    True
D    True
dtype: bool

In [ ]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  2.0
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
df.dropna()#row-wise dropping

     A    B    C    D
1  2.0  2.0  2.0  2.0

In [ ]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  2.0
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
df.dropna(thresh=3)#rows dropped which don't have 3 non-null values

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  2.0
4  5.0  5.0  NaN  5.0

In [ ]:
#To DROP PERMANANTLY use "inplace=True"

**FILLING MISSING DATA**

In [ ]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  2.0
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
df.fillna(50)

      A     B     C     D
0   1.0  50.0   1.0   1.0
1   2.0   2.0   2.0   2.0
2  50.0   3.0   3.0  50.0
3   4.0   4.0  50.0  50.0
4   5.0   5.0  50.0   5.0

In [ ]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  2.0
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
values = {'A':10,'B':20,'C':30,'D':40}

In [ ]:
df.fillna(value = values)

      A     B     C     D
0   1.0  20.0   1.0   1.0
1   2.0   2.0   2.0   2.0
2  10.0   3.0   3.0  40.0
3   4.0   4.0  30.0  40.0
4   5.0   5.0  30.0   5.0

In [ ]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  2.0
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [ ]:
df.fillna(df.mean())

     A    B    C         D
0  1.0  3.5  1.0  1.000000
1  2.0  2.0  2.0  2.000000
2  3.0  3.0  3.0  2.666667
3  4.0  4.0  2.0  2.666667
4  5.0  5.0  2.0  5.000000

**MERGING**

In [ ]:
employees = pd.DataFrame({
    "employee_id":[1,2,3,4,5],
    "name":["John","Ann","Peter","Linda","Bob"],
    "department":["HR","IT","Finance","IT","HR"]
})

In [ ]:
salaries = pd.DataFrame({
    "employee_id":[1,2,3,6,7],
    "salary":[60000,80000,65000,70000,90000],
    "bonus":[5000,10000,7000,8000,12000]
})

In [ ]:
employees

   employee_id   name department
0            1   John         HR
1            2    Ann         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [ ]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
#MERGING
pd.merge(employees,salaries,on="employee_id")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2    Ann         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees,salaries,on="employee_id",how="outer")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2    Ann         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
pd.merge(employees,salaries,on="employee_id",how="inner")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2    Ann         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees,salaries,on="employee_id",how="right")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2    Ann         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [ ]:
pd.merge(employees,salaries,on="employee_id",how="left")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2    Ann         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

**CONCATINATION**

In [ ]:
df1 = pd.DataFrame({
    "A":[1,2],
    "B":[3,4]
})

In [ ]:
df2 = pd.DataFrame({
    "A":["A","B"],
    "B":["C","D"]
})

In [ ]:
df1

   A  B
0  1  3
1  2  4

In [ ]:
df2

   A  B
0  A  C
1  B  D

In [ ]:
pd.concat([df1,df2])#concats on columns

   A  B
0  1  3
1  2  4
0  A  C
1  B  D

In [ ]:
pd.concat([df1,df2],axis=1)#Concats in rows

   A  B  A  B
0  1  3  A  C
1  2  4  B  D

**JOINING 2 DATA FRAMES**

In [ ]:
DF = pd.DataFrame({
    "name":["Alice","Bob","Charlie"]
},index = [1,2,3])

In [ ]:
DF1 = pd.DataFrame({
    "score":[85,90,75]
},index = [2,3,4])

In [ ]:
DF

      name
1    Alice
2      Bob
3  Charlie

In [ ]:
DF1

   score
2     85
3     90
4     75

In [ ]:
DF.join(DF1)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [ ]:
DF1.join(DF)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [ ]:
DF.join(DF1,how="outer")

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

**GROUP BY AND AGGREGATION**

In [ ]:
#GROUP BY
data = {
    "Category":['A','B','A','B','A','B','A','B'],
    "Store":['Store1','Store1','Store2','Store2','Store1','Store1','Store2','Store2'],
    "Sales":[100,200,150,250,300,350,400,450],
    "Quantity":[10,20,15,25,30,35,40,45],
    "Date": pd.date_range('2023-01-01',periods=8)
}

In [ ]:
data

{'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
 'Store': ['Store1',
  'Store1',
  'Store2',
  'Store2',
  'Store1',
  'Store1',
  'Store2',
  'Store2'],
 'Sales': [100, 200, 150, 250, 300, 350, 400, 450],
 'Quantity': [10, 20, 15, 25, 30, 35, 40, 45],
 'Date': DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
                '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08'],
               dtype='datetime64[ns]', freq='D')}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

  Category   Store  Sales  Quantity       Date
0        A  Store1    100        10 2023-01-01
1        B  Store1    200        20 2023-01-02
2        A  Store2    150        15 2023-01-03
3        B  Store2    250        25 2023-01-04
4        A  Store1    300        30 2023-01-05
5        B  Store1    350        35 2023-01-06
6        A  Store2    400        40 2023-01-07
7        B  Store2    450        45 2023-01-08

In [ ]:
cat = df.groupby("Category")
cat

In [ ]:
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A     950
B    1250
Name: Sales, dtype: int64

In [ ]:
Sto = df.groupby('Store')['Sales'].sum()

In [ ]:
Sto

Store
Store1     950
Store2    1250
Name: Sales, dtype: int64

In [ ]:
d = df.groupby(['Category','Store'])['Sales'].sum()
d

Category  Store
A         Store1    400
          Store2    550
B         Store1    550
          Store2    700
Name: Sales, dtype: int64

**Aggregation**

In [ ]:
#Functions- mean,median,max,min,count,std,agg

df['Sales'].mean()

np.float64(275.0)

In [ ]:
df['Sales'].median()

275.0

In [ ]:
df['Sales'].min()

100

In [ ]:
df['Sales'].max()

450

In [ ]:
df['Sales'].count()

np.int64(8)

In [ ]:
df['Sales'].std()

122.47448713915891

In [ ]:
df['Sales'].agg(['mean','median','max','min','count','std'])

mean      275.000000
median    275.000000
max       450.000000
min       100.000000
count       8.000000
std       122.474487
Name: Sales, dtype: float64

**PIVOT TABLES AND CROSS TABLES**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dp = {
    'Date': pd.date_range('2023-01-01', periods = 20),
    'Product': ['A','B','C','D'] * 5,
    'Region': ['East','West','North','South'] * 5,
    'Sales': np.random.randint(100,1000,20),
    'Units': np.random.randint(10,100,20),
    'Rep' : ['John','Mary','Bob','Alice'] * 5
}

In [ ]:
dpf = pd.DataFrame(dp)
dpf

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    826     57   John
1  2023-01-02       B   West    191     48   Mary
2  2023-01-03       C  North    330     91    Bob
3  2023-01-04       D  South    498     97  Alice
4  2023-01-05       A   East    276     81   John
5  2023-01-06       B   West    710     58   Mary
6  2023-01-07       C  North    593     28    Bob
7  2023-01-08       D  South    967     45  Alice
8  2023-01-09       A   East    941     62   John
9  2023-01-10       B   West    789     28   Mary
10 2023-01-11       C  North    401     91    Bob
11 2023-01-12       D  South    232     54  Alice
12 2023-01-13       A   East    567     57   John
13 2023-01-14       B   West    562     46   Mary
14 2023-01-15       C  North    451     84    Bob
15 2023-01-16       D  South    218     15  Alice
16 2023-01-17       A   East    972     60   John
17 2023-01-18       B   West    289     22   Mary
18 2023-01-19       C  North    536     43    Bob
19 2023-01-20       D  South    554     66  Alice

In [ ]:
dpf['Month'] = dpf['Date'].dt.month_name()

In [ ]:
dpf

         Date Product Region  Sales  Units    Rep    Month
0  2023-01-01       A   East    826     57   John  January
1  2023-01-02       B   West    191     48   Mary  January
2  2023-01-03       C  North    330     91    Bob  January
3  2023-01-04       D  South    498     97  Alice  January
4  2023-01-05       A   East    276     81   John  January
5  2023-01-06       B   West    710     58   Mary  January
6  2023-01-07       C  North    593     28    Bob  January
7  2023-01-08       D  South    967     45  Alice  January
8  2023-01-09       A   East    941     62   John  January
9  2023-01-10       B   West    789     28   Mary  January
10 2023-01-11       C  North    401     91    Bob  January
11 2023-01-12       D  South    232     54  Alice  January
12 2023-01-13       A   East    567     57   John  January
13 2023-01-14       B   West    562     46   Mary  January
14 2023-01-15       C  North    451     84    Bob  January
15 2023-01-16       D  South    218     15  Alice  January
16 2023-01-17       A   East    972     60   John  January
17 2023-01-18       B   West    289     22   Mary  January
18 2023-01-19       C  North    536     43    Bob  January
19 2023-01-20       D  South    554     66  Alice  January

In [ ]:
dpf['Quarter'] = 'Q' + dpf['Date'].dt.quarter.astype(str)

In [ ]:
dpf

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    826     57   John  January      Q1
1  2023-01-02       B   West    191     48   Mary  January      Q1
2  2023-01-03       C  North    330     91    Bob  January      Q1
3  2023-01-04       D  South    498     97  Alice  January      Q1
4  2023-01-05       A   East    276     81   John  January      Q1
5  2023-01-06       B   West    710     58   Mary  January      Q1
6  2023-01-07       C  North    593     28    Bob  January      Q1
7  2023-01-08       D  South    967     45  Alice  January      Q1
8  2023-01-09       A   East    941     62   John  January      Q1
9  2023-01-10       B   West    789     28   Mary  January      Q1
10 2023-01-11       C  North    401     91    Bob  January      Q1
11 2023-01-12       D  South    232     54  Alice  January      Q1
12 2023-01-13       A   East    567     57   John  January      Q1
13 2023-01-14       B   West    562     46   Mary  January      Q1
14 2023-01-15       C  North    451     84    Bob  January      Q1
15 2023-01-16       D  South    218     15  Alice  January      Q1
16 2023-01-17       A   East    972     60   John  January      Q1
17 2023-01-18       B   West    289     22   Mary  January      Q1
18 2023-01-19       C  North    536     43    Bob  January      Q1
19 2023-01-20       D  South    554     66  Alice  January      Q1

In [ ]:
#CREATING PIVOT TABLE
pd.pivot_table(dpf, values = 'Sales', index = 'Region',columns = 'Product')

Product      A      B      C      D
Region
East     716.4    NaN    NaN    NaN
North      NaN    NaN  462.2    NaN
South      NaN    NaN    NaN  493.8
West       NaN  508.2    NaN    NaN

In [ ]:
pd.pivot_table(dpf, values = 'Sales', index = 'Rep', columns = 'Product', aggfunc = 'sum')

Product       A       B       C       D
Rep
Alice       NaN     NaN     NaN  2469.0
Bob         NaN     NaN  2311.0     NaN
John     3582.0     NaN     NaN     NaN
Mary        NaN  2541.0     NaN     NaN

In [ ]:
pd.pivot_table(dpf, values = ['Sales','Units'], index = 'Region', columns = 'Product', aggfunc = 'sum')

          Sales                          Units
Product       A       B       C       D      A      B      C      D
Region
East     3582.0     NaN     NaN     NaN  317.0    NaN    NaN    NaN
North       NaN     NaN  2311.0     NaN    NaN    NaN  337.0    NaN
South       NaN     NaN     NaN  2469.0    NaN    NaN    NaN  277.0
West        NaN  2541.0     NaN     NaN    NaN  202.0    NaN    NaN

In [ ]:
dpf

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    826     57   John  January      Q1
1  2023-01-02       B   West    191     48   Mary  January      Q1
2  2023-01-03       C  North    330     91    Bob  January      Q1
3  2023-01-04       D  South    498     97  Alice  January      Q1
4  2023-01-05       A   East    276     81   John  January      Q1
5  2023-01-06       B   West    710     58   Mary  January      Q1
6  2023-01-07       C  North    593     28    Bob  January      Q1
7  2023-01-08       D  South    967     45  Alice  January      Q1
8  2023-01-09       A   East    941     62   John  January      Q1
9  2023-01-10       B   West    789     28   Mary  January      Q1
10 2023-01-11       C  North    401     91    Bob  January      Q1
11 2023-01-12       D  South    232     54  Alice  January      Q1
12 2023-01-13       A   East    567     57   John  January      Q1
13 2023-01-14       B   West    562     46   Mary  January      Q1
14 2023-01-15       C  North    451     84    Bob  January      Q1
15 2023-01-16       D  South    218     15  Alice  January      Q1
16 2023-01-17       A   East    972     60   John  January      Q1
17 2023-01-18       B   West    289     22   Mary  January      Q1
18 2023-01-19       C  North    536     43    Bob  January      Q1
19 2023-01-20       D  South    554     66  Alice  January      Q1

**CROSS TABLES**

In [ ]:
pd.crosstab(dpf['Region'],dpf['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [ ]:
pd.crosstab(dpf['Rep'],dpf['Region'])

Region  East  North  South  West
Rep
Alice      0      0      5     0
Bob        0      5      0     0
John       5      0      0     0
Mary       0      0      0     5

**BASIC OPERATIONS ON DATA FRAMES**

In [ ]:
d1 = pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
})

In [ ]:
d1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
d1.shape

(5, 3)

In [ ]:
d1.columns

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
d1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
#Addition ops
d1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [ ]:
#Subtraction
d1['B'] - 5

0     5
1    15
2    25
3    35
4    45
Name: B, dtype: int64

In [ ]:
#Multiplication
d1['C'] * 2

0     200
1     400
2     600
3     800
4    1000
Name: C, dtype: int64

In [ ]:
#Division
d1['C'] // 2

0     50
1    100
2    150
3    200
4    250
Name: C, dtype: int64

In [ ]:
d1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
d1['A'] ** 2

0     1
1     4
2     9
3    16
4    25
Name: A, dtype: int64

**APPLYING FUNCTIONS ON DATA FRAMES**

In [ ]:
def square(x):
  return x**2

In [ ]:
d1['A'].apply(square)

0     1
1     4
2     9
3    16
4    25
Name: A, dtype: int64

In [ ]:
#LAMBDA FUNCTION
d1['D'] = d1['A'].apply(lambda x : x ** 2)

In [ ]:
d1

   A   B    C   D
0  1  10  100   1
1  2  20  200   4
2  3  30  300   9
3  4  40  400  16
4  5  50  500  25